global using static System.Console;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using SimpleTodoList.Library.Models;
global using SimpleTodoList.Library.Persistances;
global using SimpleTodoList.Library.Repositories;
global using SimpleTodoList.Library.Services;
global using SimpleTodoList.Library.Databases;
