global using static System.Console;
global using System.Data;
global using Microsoft.Data.Sqlite;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Dapper;
global using ConsoleSimpleTodoList.Models;
global using ConsoleSimpleTodoList.Persistances;
